[package]
name = "local-dictate-ui"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
directories = "6.0.0"
eframe = "0.34.3"
local-dictate-core = { path = "../local-dictate-core" }
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2"
